Remove useless method DBDriver::Result::freeResult() #80
seznam/SuperiorMySqlpp pull request #101
Opened 2018-08-17 06:49 UTC by tomasprochazka2

The method DBDriver::Result::freeResult() is never used and thus can be removed

2018-08-21 06:42 UTC, MrWarlockX commented on include/superior_mysqlpp/low_level/dbdriver.hpp
> +
Please remove unnecessary whitespaces.

2018-08-28 06:06 UTC, majcl requested changes

2018-08-28 06:06 UTC, majcl commented on include/superior_mysqlpp/low_level/dbdriver.hpp
> -            auto freeResult()
IMHO would be better to leave it here, but call `mysql_free_result` with same condition as in close(), make it noexcept, and possibly remove close() method and instead use this one? @smradCZ ?

2018-08-30 06:48 UTC, majcl approved these changes

2018-08-30 07:07 UTC, merged