Log errors in default logger + refactor
seznam/SuperiorMySqlpp pull request #111
Opened 2019-05-23 17:44 UTC by OpatrilPeter

Some minor formating may still be in order, but the logic should be ok.

2019-05-24 14:49 UTC, OpatrilPeter commented on include/superior_mysqlpp/logging.hpp
> +            std::atomic_flag stderrLogWriteLock{};
Global variables are usually warning sing, so I'm pointing it out. My previous solution passed `atomic_lock`s around as they used previously, this one leads to less boilerplate with no obvious disadvantage for me.

2019-05-27 11:12 UTC, OpatrilPeter commented on include/superior_mysqlpp/logging.hpp
> +            std::atomic_flag stderrLogWriteLock{};
My bad, this rewrite looks nicer then original approach, but global variables in header-only lib are no-no, of course.

2019-05-28 11:51 UTC, smradCZ requested changes
Good point, it's much better to have only one definition of log messages on one place.
There are some small mistakes in doxygen comments, please fix them and then we can merge your changes.
Thanks a lot

2019-05-28 11:51 UTC, smradCZ commented on include/superior_mysqlpp/logging.hpp
> +         * @param args
Please fill up all parameters to doxygen comment

2019-05-28 11:51 UTC, smradCZ commented on include/superior_mysqlpp/utils.hpp
> +     * Writes variable number of arguments into arbitrary std(-like) stream.
It writes *exactly one* argument

2019-05-28 11:51 UTC, smradCZ commented on include/superior_mysqlpp/utils.hpp
> +    /**
Please fill full doxydoc here to keep whole class documented.

2019-05-28 16:00 UTC, OpatrilPeter commented on include/superior_mysqlpp/utils.hpp
> +     * Writes variable number of arguments into arbitrary std(-like) stream.
This is by design, goal is that overloads should share the documentation. Apparently, `@overload` was needed for that, judging by other examples in this codebase it wasn't clear.

2019-05-28 16:00 UTC, OpatrilPeter commented on include/superior_mysqlpp/logging.hpp
> +         * @param args
Well spotted, forgot about lock being added in last refactor.

2019-05-29 06:02 UTC, smradCZ approved these changes

2019-05-29 07:15 UTC, merged