Added ConnectionConfig including tests
seznam/SuperiorMySqlpp pull request #22
Opened 2016-11-01 16:13 UTC by jirislav

ConnectionConfig is a class which should solve the problem with ambiguity while calling Connection c'tor with only host / socket defined (compiler error)

Here is the default value for c'tor with socket unset for socket so that there is no more ambiguity and is added a ConnectionConfig class instead. It provides two static factory methods for both TCP Connection & Socketed Connection with as much default values as possible.

Tests were working in a way that the host (machine the tests are ran from) is connected to Dockerized MySQL server via TCP using Docker IP by default. 

So - in order to create tests for socketed connection I've come up with a socket -> socket tunnel via TCP. It works in a way that host creates socket, where the tests try to connect. This socket is only a traffic forwarder to 3307 port of the Docker instance of tested MySQL server. The docker instance has listener on port 3307 forwarding all traffic to mysqld socket. So there actually is a socketed connection - but relies on TCP. (Any ideas how to do socketed connection tests better while is the testing environment still being in Docker?)

The work was initiated by Issue #4

2017-04-06 15:43 UTC, danopernis reviewed
Nice work, please work on fixes, squash, rebase onto devel and I will review again.

2017-04-06 15:43 UTC, danopernis commented on db/mysql-socket-tunnel-3307
> +socat TCP-LISTEN:3307,reuseaddr,fork UNIX-CLIENT:/var/run/mysqld/mysqld.sock
Please use `exec socat ...` to save one process

2017-04-06 15:43 UTC, danopernis commented on .gitignore
> +*.swp
Please make this into separate commit

2017-04-06 15:43 UTC, danopernis commented on include/superior_mysqlpp/config.hpp
> +            const struct SslConfiguration sslConfig;
Please use `SuperiorMySqlpp::Optional<SslConfiguration>` instead of struct and bool

2017-04-06 15:43 UTC, danopernis commented on include/superior_mysqlpp/config.hpp
> +            virtual ~ConnectionConfig() = default;
I believe both members are redundant. Class is not intended for polymorphic usage and is indeed copy constructible

2017-04-06 15:43 UTC, danopernis commented on include/superior_mysqlpp/config.hpp
> +    class ConnectionConfig {
Please rename this to ConnectionConfiguration for consistency with SslConfiguration

2017-04-06 15:43 UTC, danopernis commented on include/superior_mysqlpp/connection_def.hpp
> +
Do not mix whitespace fixes with functional commits

2017-04-06 15:43 UTC, danopernis commented on tests/makefile
> +#source_files :=$(sort $(shell find ./ -name "*.cpp" -not -name "*.odr.cpp" | egrep "main|connection.cpp"))
Why is this commented out?

2017-04-06 15:43 UTC, danopernis commented on tests/runtest.sh
> +if [ ! "$(dpkg -l | grep socat)" ]; then
I would not bother with this, either it is installed and everything is OK, or it is not and script will fail anyway. You are not checking whether `docker` is installed, why would you special case socat?

2018-04-05 12:23 UTC, jbouska567 commented on db/Dockerfile
> +    socat \
what is this?

2018-04-10 10:52 UTC, pnov reviewed
ok

2018-04-24 13:24 UTC, majcl requested changes
Please add also description and example to Readme.md

2018-04-24 15:22 UTC, smradCZ commented
README.md is updated, please check it.

2018-04-25 04:33 UTC, majcl approved these changes

2018-04-25 07:17 UTC, merged