Replace `string_view::to_string` with string ctor
seznam/SuperiorMySqlpp pull request #47
Opened 2017-11-29 10:38 UTC by OpatrilPeter

Method `to_string` in experimental (pre-C++17) version of `std::string_view` was removed from C++17 standard. New preferred (and backward compatible) way is calling std::string constructor.

2017-12-06 11:51 UTC, majcl requested changes

2017-12-06 11:51 UTC, majcl commented on include/superior_mysqlpp/dnsa_connection_pool.hpp
> +                    addresses.emplace_back(std::string(endpoint.address()));
This is boost::asio::ip::address class and it has to_string() member method. Are you really sure, you don't want to use it? Why? It has nothing to do with std:string_view.

2017-12-07 13:30 UTC, OpatrilPeter commented on include/superior_mysqlpp/dnsa_connection_pool.hpp
> +                    addresses.emplace_back(std::string(endpoint.address()));
You were indeed correct, that was an oversight and shall be already fixed

2017-12-13 10:21 UTC, majcl approved these changes

2017-12-13 10:23 UTC, merged