Fix exact int types
seznam/SuperiorMySqlpp pull request #68
Opened 2018-03-02 17:23 UTC by OpatrilPeter

As SQL uses exact-width integer types, using native C ints may cause portability issues - this PR rewrites such occurences.

Note that this currently causes warnings in test suite.
They are not errors (only hint at usage of inappropriate type) but probably should be fixed.

2018-09-10 06:20 UTC, majcl requested changes

2018-09-10 06:20 UTC, majcl commented on include/superior_mysqlpp/sql_types.hpp
> +        using TinyInt = int_fast8_t;
I don't think it's good idea. These types can be of arbitrary size. And it forces you to use same types in your app. Moreover, possible serialization of these types can be non-portable.

2018-09-10 06:20 UTC, majcl commented on include/superior_mysqlpp/prepared_statements/initialize_bindings.hpp
> +            using PureType_t = to_fixed_width_int_t<std::decay_t<T>>;
I don't see why?

2018-09-27 17:01 UTC, OpatrilPeter commented on include/superior_mysqlpp/sql_types.hpp
> +        using TinyInt = int_fast8_t;
Good idea compared to what? You are right that these definitions are not acceptable for serialization, but they do not try to be - they are exactly comparable to current definitions. For example - `int` in C is defined with identical constraints as `int_fast16_t`, but is way less clear about those. Take `MediumInt` - this one has 24bits, so on architecture where int is 16b only current definition will break.

2019-02-12 17:08 UTC, OpatrilPeter commented on include/superior_mysqlpp/prepared_statements/initialize_bindings.hpp
> +            using PureType_t = to_fixed_width_int_t<std::decay_t<T>>;
I don't remember this context exactly, but the reason for `to_fixed_width_int_t` in general is to deal with the fact that DB type is defined to be, say, 64b - so on your architecture you can use `long` and `long long` - however, those types are not equivalent for purposes of `std::is_same` or similar - so this normalizes types to matching fixed width.

2019-06-11 09:07 UTC, majcl commented on include/superior_mysqlpp/sql_types.hpp
> +        using TinyInt = int_fast8_t;
C API sdk defines exactly, what mysql and C-types equivalents. See
https://dev.mysql.com/doc/refman/8.0/en/c-api-prepared-statement-type-codes.html

2019-06-11 09:22 UTC, majcl commented on include/superior_mysqlpp/prepared_statements/initialize_bindings.hpp
> +            using PureType_t = to_fixed_width_int_t<std::decay_t<T>>;
Same case as above.

2019-06-12 17:14 UTC, OpatrilPeter commented on include/superior_mysqlpp/sql_types.hpp
> +        using TinyInt = int_fast8_t;
Excellent reference, thanks for bringing it up. I was under false impression that MySQL library we use does not specify it (as is the case in many other details).
In this light I'd say this PR is not needed, I'll update it to just contain the reference above in form of a comment.

2019-06-12 17:18 UTC, OpatrilPeter commented on include/superior_mysqlpp/prepared_statements/initialize_bindings.hpp
> +            using PureType_t = to_fixed_width_int_t<std::decay_t<T>>;
Right, the ambiguity I mentioned is cleanly resolved with the mentioned reference.
One can argue that users depending on interface of underlying C library is violating our encapsulation, but it's only theoretical issue.

2019-06-13 13:47 UTC, smradCZ approved these changes

2019-06-13 14:25 UTC, majcl approved these changes

2019-06-13 14:26 UTC, merged